const express = require('express');
const router = express.Router();
const bcrypt = require('bcryptjs');
const crypto = require('crypto'); 
const Task = require('../models/Task');
// --- MODELS ---
const User = require('../models/User');
const Log = require('../models/Log');
const Project = require('../models/Project');
const Feed = require('../models/Feed');
const Prospect = require('../models/Prospect');
const LeadGen = require('../models/LeadGen');
const { register, login, forgotPassword, resetPassword } = require('../controllers/authController');
// --- MIDDLEWARE ---
const { authorize } = require('../middleware/roleCheck');
const getWelcomeTemplate = require('../templates/welcomeEmail');
// --- USER MANAGEMENT ROUTES ---

router.get('/users', authorize('Admin', 'Project Manager', 'Sales Manager','Sales'), async (req, res) => {
  try {
    let filter = {};
    if (req.user.role === 'Sales Manager') {
      filter = { role: 'Sales' };
    }
    
    // 1. Fetch the users matching the filter
    const users = await User.find(filter).select('-password').sort({ createdAt: -1 });

    // 2. Attach counts for Prospects and Leads to each user
    const usersWithStats = await Promise.all(users.map(async (user) => {
      // Convert the Mongoose document to a plain JavaScript object
      const userObj = user.toObject();

      // Count Prospects in this rep's bucket
      // We look for 'salesRepId' matching the user's ID
      userObj.prospectCount = await Prospect.countDocuments({ 
        salesRepId: user._id 
      });

      // Count Leads generated by this rep
      userObj.leadCount = await LeadGen.countDocuments({ 
        salesRepId: user._id 
      });

      return userObj;
    }));

    // 3. Send the enriched data back to the frontend
    res.json(usersWithStats);
  } catch (err) {
    console.error("Error in /users route:", err);
    res.status(500).json({ error: err.message });
  }
});

// Add this at the very top of your adminRoutes.js file
const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  service: 'gmail',
  host: 'smtp.gmail.com',
  port: 587,
  secure: false,
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS, 
  },
  tls: {
    rejectUnauthorized: false
  }
});
// Place this right after your User Management routes but BEFORE any /:id routes
router.post('/change-password', authorize('Admin', 'Sales Manager', 'Sales', 'Project Manager', 'Developer'), async (req, res) => {
  try {
    const { currentPassword, newPassword } = req.body;
    const user = await User.findById(req.user._id);

    if (!user) return res.status(404).json({ error: "User not found" });

    const isMatch = await bcrypt.compare(currentPassword, user.password);
    if (!isMatch) {
      return res.status(400).json({ error: "Current password incorrect" });
    }

    const salt = await bcrypt.genSalt(10);
    user.password = await bcrypt.hash(newPassword, salt);
    await user.save();
    
    res.json({ message: "Password updated successfully!" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
// --- UPDATED POST METHOD ---
router.post('/users', authorize('Admin', 'Project Manager', 'Sales Manager'), async (req, res) => {
  try {
    const { name, email, password, role } = req.body;
    let finalRole = role;

    // Authorization Logic for Role Creation
    if (req.user.role === 'Sales Manager') {
      finalRole = 'Sales'; 
    } else if (req.user.role === 'Project Manager') {
      finalRole = 'Client'; 
    }

    const existingUser = await User.findOne({ email });
    if (existingUser) return res.status(400).json({ error: "Email already in use" });

    // Use provided password or default to "123456"
    const cleanPassword = String(password || "123456");
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(cleanPassword, salt);

    const newUser = new User({ 
      name, 
      email, 
      password: hashedPassword, 
      role: finalRole 
    });

    await newUser.save();
    const emailHtml = getWelcomeTemplate(name, email, cleanPassword, finalRole," http://192.168.1.105:5173/");
    // --- BACKGROUND EMAIL LOGIC ---
    // We do NOT "await" this so the frontend gets a response immediately
    const mailOptions = {
      from: `"KUIPER SYSTEM" <${process.env.EMAIL_USER}>`,
      to: email,
      subject: 'Your System Access Credentials',
      html:emailHtml
    };

    transporter.sendMail(mailOptions)
      .then(info => console.log("✅ Email sent successfully:", info.messageId))
      .catch(err => console.error("❌ Email failed to send:", err.message));

    // --- LOGGING ---
    try {
      await Log.create({
        actionType: 'USER_CREATED',
        performerId: req.user._id,
        details: `Created ${finalRole}: ${name} (By ${req.user.role})`,
        timestamp: new Date()
      });
    } catch (logErr) {
      console.error("Non-critical Log Error:", logErr.message);
    }

    res.status(201).json(newUser);
  } catch (err) {
    console.error("Error creating user:", err);
    res.status(400).json({ error: err.message });
  }
});
router.put('/users/:id', authorize('Admin'), async (req, res) => {
  try {
    const { name, email, role } = req.body;
    const updatedUser = await User.findByIdAndUpdate(
      req.params.id,
      { name, email, role },
      { new: true, runValidators: true }
    );
    res.json(updatedUser);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.delete('/users/:id', authorize('Admin'), async (req, res) => {
  try {
    await User.findByIdAndDelete(req.params.id);
    res.json({ message: "User deleted successfully" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// --- AUDIT & ANALYTICS ---

// FIX 1: Added 'Project Manager' to authorize so PM can access this route
// FIX 2: PM and Admin both see ALL logs — only Sales sees their own
router.get('/analytics', authorize('Admin', 'Sales', 'Project Manager', 'Sales Manager'), async (req, res) => {
  try {
    const { page = 1, limit = 10 } = req.query;

    if (!req.user) return res.status(401).json({ error: "Unauthorized" });

    let filter = {};
    
    if (req.user.role === 'Sales') {
      filter = { performerId: req.user._id };
    } else if (req.user.role === 'Sales Manager') {
      // Sales Manager sees all logs related to Sales activity
      const salesActions = ['USER_CREATED', 'PROSPECT_IMPORTED', 'LEAD_GENERATED', 'FOLLOW_UP_SET', 'LEAD_CLOSED'];
      filter = { actionType: { $in: salesActions } };
    }
    // Admin and PM see {} (everything)

    const logs = await Log.find(filter)
      .sort({ timestamp: -1 })
      .limit(parseInt(limit))
      .skip((parseInt(page) - 1) * parseInt(limit))
      .populate('performerId', 'name role')
      .lean();

    const count = await Log.countDocuments(filter);

    res.json({
      logs,
      totalPages: Math.ceil(count / limit) || 1,
      currentPage: parseInt(page),
      totalLogs: count
    });
  } catch (err) {
    res.status(500).json({ error: "Internal Server Error", details: err.message });
  }
});

// --- PROJECT MANAGEMENT ROUTES ---

router.get('/projects', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const data = await Project.find()
      .populate('clients', 'name email')
      .populate('projectManager', 'name email')
      .populate({
        path: 'feeds',
        populate: { path: 'assignedDevelopers', select: 'name', model: 'User' }
      });
    res.json(data);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// Replace the POST '/projects' route in your adminRoutes.js with this:

const COUNTRY_MAP = {
  "Afghanistan": "AF", "Albania": "AL", "Algeria": "DZ", 
  "Australia": "AU", "Brazil": "BR", "Canada": "CA", 
  "China": "CN", "France": "FR", "Germany": "DE", 
  "India": "IN", "Indonesia": "ID", "Italy": "IT", 
  "Japan": "JP", "Mexico": "MX", "Netherlands": "NL", 
  "Nigeria": "NG", "Pakistan": "PK", "Russia": "RU", 
  "Saudi Arabia": "SA", "Singapore": "SG", "South Africa": "ZA", 
  "South Korea": "KR", "Spain": "ES", "Turkey": "TR", 
  "United Arab Emirates": "AE", "United Kingdom": "GB", 
  "United States": "US", "Vietnam": "VN"
};

router.post('/projects', authorize('Admin', 'Project Manager','Sales'), async (req, res) => {
  try {
    const { name, clients, description, country, industry, projectManager } = req.body;

    // 1. Generate Serial Number
    const projectCount = await Project.countDocuments();
    const serialNumber = String(projectCount + 1).padStart(4, '0');
    
    // 2. Get 2-letter Country Code
    const countryCode = COUNTRY_MAP[country] || (country ? country.substring(0, 2).toUpperCase() : 'XX');
    
    // 3. Get 4-letter Industry Code (uppercase)
    const industryCode = (industry || 'GEN').toUpperCase().substring(0, 4);
    
    // 4. Format: TDS0011-ECOM | AE | Books Data Extraction
    const fullFormattedName = `TDS${serialNumber}-${industryCode} | ${countryCode} | ${name}`;

    const newProject = new Project({
      name: fullFormattedName,              // Full formatted name
      clients,
      description,
      adminId: req.user._id,
      projectManager: projectManager || (req.user.role === 'Project Manager' ? req.user._id : null),
      country,
      industry,
      projectCustomId: fullFormattedName    // Same formatted name
    });

    await newProject.save();

    // Log creation
    try {
      await Log.create({
        actionType: 'PROJECT_CREATED',
        performerId: req.user._id,
        details: `Created project: ${name} [${fullFormattedName}] (By ${req.user.role})`,
        timestamp: new Date()
      });
    } catch (logErr) {
      console.error("Non-critical Log Error:", logErr.message);
    }

    res.status(201).json(newProject);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
router.put('/projects/:id', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const updatedProject = await Project.findByIdAndUpdate(req.params.id, req.body, { new: true });
    res.json(updatedProject);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

router.delete('/projects/:id', authorize('Admin'), async (req, res) => {
  try {
    const project = await Project.findByIdAndDelete(req.params.id);
    if (!project) return res.status(404).json({ message: "Project not found" });

    if (project.feeds && project.feeds.length > 0) {
      await Feed.deleteMany({ _id: { $in: project.feeds } });
    }
    res.json({ message: "Project and its feeds deleted successfully" });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// --- FEED MANAGEMENT ROUTES ---

router.post('/feeds', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const {
      name,
      assignedDevelopers,
      projectId,
      feedType,
      weekDay
    } = req.body;

    const newFeed = await Feed.create({
      name,
      assignedDevelopers,
      projectId,
      adminId: req.user._id,
      feedType: feedType || 'Daily',

      // NEW
      weekDay: feedType === 'Weekly'
        ? weekDay
        : null
    });

    await Project.findByIdAndUpdate(
      projectId,
      { $push: { feeds: newFeed._id } }
    );

    try {
      await Log.create({
        actionType: 'FEED_CREATED',
        performerId: req.user._id,
        details: `Created feed: ${name} (By ${req.user.role})`,
        timestamp: new Date()
      });
    } catch (logErr) {
      console.error("Non-critical Log Error:", logErr.message);
    }

    res.status(201).json(newFeed);

  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
router.post('/change-password', async (req, res) => {
  try {
    const { currentPassword, newPassword } = req.body;
    // req.user.id comes from your 'protect' middleware
    const user = await User.findById(req.user.id);

    // Verify current password
    const isMatch = await bcrypt.compare(currentPassword, user.password);
    if (!isMatch) {
      return res.status(400).json({ error: "Current password does not match our records." });
    }

    // Hash new password
    const salt = await bcrypt.genSalt(10);
    user.password = await bcrypt.hash(newPassword, salt);
    
    await user.save();
    res.json({ message: "Password updated successfully!" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
router.put('/feeds/:id', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const {
      name,
      assignedDevelopers,
      feedType,
      weekDay
    } = req.body;

    const updatedFeed = await Feed.findByIdAndUpdate(
      req.params.id,
      {
        name,
        assignedDevelopers,
        feedType,

        // NEW
        weekDay: feedType === 'Weekly'
          ? weekDay
          : null
      },
      {
        new: true,
        runValidators: true
      }
    );

    res.json(updatedFeed);

  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.delete('/feeds/:id', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const feed = await Feed.findById(req.params.id);
    if (!feed) return res.status(404).json({ error: "Feed not found" });
    await Project.findByIdAndUpdate(feed.projectId, { $pull: { feeds: feed._id } });
    await Feed.findByIdAndDelete(req.params.id);
    res.json({ message: "Feed deleted successfully" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// --- HELPER ROUTES ---

router.get('/users/clients', authorize('Admin', 'Sales', 'Project Manager', 'Sales Manager'), async (req, res) => {
  try {
    const clients = await User.find({ role: 'Client' }).select('name email');
    res.json(clients);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.get('/users/developers', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const developers = await User.find({ role: 'Developer' }).select('name email');
    res.json(developers);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.get('/users/project-managers', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const projectManagers = await User.find({ role: 'Project Manager' })
      .select('name email')
      .sort({ name: 1 });
    res.json(projectManagers);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.get('/project-managers', authorize('Admin', 'Project Manager', 'Sales'), async (req, res) => {
  try {
    const managers = await User.find({ role: 'Project Manager' }).select('name _id');
    res.json(managers);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.patch('/feeds/:id/assign', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const { developerId } = req.body;
    const updatedFeed = await Feed.findByIdAndUpdate(
      req.params.id,
      { $addToSet: { assignedDevelopers: developerId } },
      { new: true }
    ).populate('assignedDevelopers', 'name email');
    res.json(updatedFeed);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
router.get('/users/sales-reps', authorize('Admin', 'Sales Manager'), async (req, res) => {
  try {
    const reps = await User.find({ role: 'Sales' }).select('name email');
    res.json(reps);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
}); 
router.get('/logs', authorize('Admin', 'Project Manager', 'Sales Manager'), async (req, res) => {
  try {
    let filter = {};
    if (req.user.role === 'Sales Manager') {
        filter = { actionType: { $in: ['LEAD_GENERATED', 'FOLLOW_UP_SET', 'PROSPECT_IMPORTED'] } };
    }

    const logs = await Log.find(filter)
      .populate('performerId', 'name role')
      .sort({ timestamp: -1 })
      .limit(50);
    res.status(200).json(logs);
  } catch (error) {
    res.status(500).json({ error: "Could not fetch activity bucket" });
  }
});

router.post('/tasks', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const { title, description, feedId, projectId, developerId, deadline, priority } = req.body;
    const newTask = new Task({
      title, description, feedId, projectId, developerId,
      assignedBy: req.user._id, deadline, priority
    });
    await newTask.save();
    res.status(201).json(newTask);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

router.post('/tasks/create', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const newTask = new Task({
      projectId: req.body.projectId,
      feedId: req.body.feedId,
      performerId: req.user._id, // always use logged-in user
      targetUsers: req.body.assignedDevelopers,
      details: req.body.details
    });
    await newTask.save();
    res.status(201).json({ message: "Task inserted into tasks table!" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;