const express = require('express');
const router = express.Router();
const bcrypt = require('bcryptjs');
const Task = require('../models/Task');
// --- MODELS ---
const User = require('../models/User');
const Log = require('../models/Log');
const Project = require('../models/Project');
const Feed = require('../models/Feed');
const Prospect = require('../models/Prospect');
const LeadGen = require('../models/LeadGen');
// --- MIDDLEWARE ---
const { authorize } = require('../middleware/roleCheck');

// --- USER MANAGEMENT ROUTES ---

router.get('/users', authorize('Admin', 'Project Manager', 'Sales Manager','Sales'), async (req, res) => {
  try {
    let filter = {};
    if (req.user.role === 'Sales Manager') {
      filter = { role: 'Sales' };
    }
    
    // 1. Fetch the users matching the filter
    const users = await User.find(filter).select('-password').sort({ createdAt: -1 });

    // 2. Attach counts for Prospects and Leads to each user
    const usersWithStats = await Promise.all(users.map(async (user) => {
      // Convert the Mongoose document to a plain JavaScript object
      const userObj = user.toObject();

      // Count Prospects in this rep's bucket
      // We look for 'salesRepId' matching the user's ID
      userObj.prospectCount = await Prospect.countDocuments({ 
        salesRepId: user._id 
      });

      // Count Leads generated by this rep
      userObj.leadCount = await LeadGen.countDocuments({ 
        salesRepId: user._id 
      });

      return userObj;
    }));

    // 3. Send the enriched data back to the frontend
    res.json(usersWithStats);
  } catch (err) {
    console.error("Error in /users route:", err);
    res.status(500).json({ error: err.message });
  }
});

router.post('/users', authorize('Admin', 'Project Manager', 'Sales Manager'), async (req, res) => {
  try {
    const { name, email, password, role } = req.body;

    let finalRole = role;
    
    // Authorization Logic for Role Creation
    if (req.user.role === 'Sales Manager') {
      finalRole = 'Sales'; // Sales Managers can only create Sales Reps
    } else if (req.user.role === 'Project Manager') {
      finalRole = 'Client'; // PMs can only create Clients
    }
    // Only Admin can create Sales Managers or Project Managers

    const existingUser = await User.findOne({ email });
    if (existingUser) return res.status(400).json({ error: "Email already in use" });

    const cleanPassword = String(password || "123456");
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(cleanPassword, salt);

    const newUser = new User({ name, email, password: hashedPassword, role: finalRole });
    await newUser.save();

    try {
      await Log.create({
        actionType: 'USER_CREATED',
        performerId: req.user._id,
        details: `Created ${finalRole}: ${name} (By ${req.user.role})`,
        timestamp: new Date()
      });
    } catch (logErr) {
      console.error("Non-critical Log Error:", logErr.message);
    }

    res.status(201).json(newUser);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

router.put('/users/:id', authorize('Admin'), async (req, res) => {
  try {
    const { name, email, role } = req.body;
    const updatedUser = await User.findByIdAndUpdate(
      req.params.id,
      { name, email, role },
      { new: true, runValidators: true }
    );
    res.json(updatedUser);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.delete('/users/:id', authorize('Admin'), async (req, res) => {
  try {
    await User.findByIdAndDelete(req.params.id);
    res.json({ message: "User deleted successfully" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// --- AUDIT & ANALYTICS ---

// FIX 1: Added 'Project Manager' to authorize so PM can access this route
// FIX 2: PM and Admin both see ALL logs — only Sales sees their own
router.get('/analytics', authorize('Admin', 'Sales', 'Project Manager', 'Sales Manager'), async (req, res) => {
  try {
    const { page = 1, limit = 10 } = req.query;

    if (!req.user) return res.status(401).json({ error: "Unauthorized" });

    let filter = {};
    
    if (req.user.role === 'Sales') {
      filter = { performerId: req.user._id };
    } else if (req.user.role === 'Sales Manager') {
      // Sales Manager sees all logs related to Sales activity
      const salesActions = ['USER_CREATED', 'PROSPECT_IMPORTED', 'LEAD_GENERATED', 'FOLLOW_UP_SET', 'LEAD_CLOSED'];
      filter = { actionType: { $in: salesActions } };
    }
    // Admin and PM see {} (everything)

    const logs = await Log.find(filter)
      .sort({ timestamp: -1 })
      .limit(parseInt(limit))
      .skip((parseInt(page) - 1) * parseInt(limit))
      .populate('performerId', 'name role')
      .lean();

    const count = await Log.countDocuments(filter);

    res.json({
      logs,
      totalPages: Math.ceil(count / limit) || 1,
      currentPage: parseInt(page),
      totalLogs: count
    });
  } catch (err) {
    res.status(500).json({ error: "Internal Server Error", details: err.message });
  }
});

// --- PROJECT MANAGEMENT ROUTES ---

router.get('/projects', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const data = await Project.find()
      .populate('clients', 'name email')
      .populate('projectManager', 'name email')
      .populate({
        path: 'feeds',
        populate: { path: 'assignedDevelopers', select: 'name', model: 'User' }
      });
    res.json(data);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

router.post('/projects', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const { name, clients, description, adminId, country, industry, projectManager } = req.body;

    const projectCount = await Project.countDocuments();
    const sequence = String(projectCount + 1).padStart(4, '0');
    const upperName = name.toUpperCase();
    const upperIndustry = industry.toUpperCase();
    const formattedCountry = country.toUpperCase().replace(/\s+/g, "-");
    const customId = `TDS${sequence}-${upperIndustry} | ${formattedCountry} | ${upperName}`;

    const newProject = new Project({
      name,
      clients,
      description,
      adminId: req.user._id, // always use the logged-in user, not the body
      projectManager: projectManager || (req.user.role === 'Project Manager' ? req.user._id : null),
      country,
      industry,
      projectCustomId: customId
    });

    await newProject.save();

    // FIX 3: Log the project creation with the correct performerId
    try {
      await Log.create({
        actionType: 'PROJECT_CREATED',
        performerId: req.user._id, // always the logged-in user
        details: `Created project: ${name} [${customId}] (By ${req.user.role})`,
        timestamp: new Date()
      });
    } catch (logErr) {
      console.error("Non-critical Log Error:", logErr.message);
    }

    res.status(201).json(newProject);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.put('/projects/:id', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const updatedProject = await Project.findByIdAndUpdate(req.params.id, req.body, { new: true });
    res.json(updatedProject);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

router.delete('/projects/:id', authorize('Admin'), async (req, res) => {
  try {
    const project = await Project.findByIdAndDelete(req.params.id);
    if (!project) return res.status(404).json({ message: "Project not found" });

    if (project.feeds && project.feeds.length > 0) {
      await Feed.deleteMany({ _id: { $in: project.feeds } });
    }
    res.json({ message: "Project and its feeds deleted successfully" });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// --- FEED MANAGEMENT ROUTES ---

router.post('/feeds', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const { name, assignedDevelopers, projectId, feedType } = req.body;

    const newFeed = await Feed.create({
      name,
      assignedDevelopers,
      projectId,
      adminId: req.user._id, // always use logged-in user
      feedType: feedType || 'Daily'
    });

    await Project.findByIdAndUpdate(projectId, { $push: { feeds: newFeed._id } });

    try {
      await Log.create({
        actionType: 'FEED_CREATED',
        performerId: req.user._id,
        details: `Created feed: ${name} (By ${req.user.role})`,
        timestamp: new Date()
      });
    } catch (logErr) {
      console.error("Non-critical Log Error:", logErr.message);
    }

    res.status(201).json(newFeed);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.put('/feeds/:id', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const { name, assignedDevelopers, feedType } = req.body;
    const updatedFeed = await Feed.findByIdAndUpdate(
      req.params.id,
      { name, assignedDevelopers, feedType },
      { new: true, runValidators: true }
    );
    res.json(updatedFeed);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.delete('/feeds/:id', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const feed = await Feed.findById(req.params.id);
    if (!feed) return res.status(404).json({ error: "Feed not found" });
    await Project.findByIdAndUpdate(feed.projectId, { $pull: { feeds: feed._id } });
    await Feed.findByIdAndDelete(req.params.id);
    res.json({ message: "Feed deleted successfully" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// --- HELPER ROUTES ---

router.get('/users/clients', authorize('Admin', 'Sales', 'Project Manager', 'Sales Manager'), async (req, res) => {
  try {
    const clients = await User.find({ role: 'Client' }).select('name email');
    res.json(clients);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.get('/users/developers', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const developers = await User.find({ role: 'Developer' }).select('name email');
    res.json(developers);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.get('/users/project-managers', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const projectManagers = await User.find({ role: 'Project Manager' })
      .select('name email')
      .sort({ name: 1 });
    res.json(projectManagers);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.get('/project-managers', authorize('Admin', 'Project Manager', 'Sales'), async (req, res) => {
  try {
    const managers = await User.find({ role: 'Project Manager' }).select('name _id');
    res.json(managers);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.patch('/feeds/:id/assign', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const { developerId } = req.body;
    const updatedFeed = await Feed.findByIdAndUpdate(
      req.params.id,
      { $addToSet: { assignedDevelopers: developerId } },
      { new: true }
    ).populate('assignedDevelopers', 'name email');
    res.json(updatedFeed);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
router.get('/users/sales-reps', authorize('Admin', 'Sales Manager'), async (req, res) => {
  try {
    const reps = await User.find({ role: 'Sales' }).select('name email');
    res.json(reps);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
}); 
router.get('/logs', authorize('Admin', 'Project Manager', 'Sales Manager'), async (req, res) => {
  try {
    let filter = {};
    if (req.user.role === 'Sales Manager') {
        filter = { actionType: { $in: ['LEAD_GENERATED', 'FOLLOW_UP_SET', 'PROSPECT_IMPORTED'] } };
    }

    const logs = await Log.find(filter)
      .populate('performerId', 'name role')
      .sort({ timestamp: -1 })
      .limit(50);
    res.status(200).json(logs);
  } catch (error) {
    res.status(500).json({ error: "Could not fetch activity bucket" });
  }
});

router.post('/tasks', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const { title, description, feedId, projectId, developerId, deadline, priority } = req.body;
    const newTask = new Task({
      title, description, feedId, projectId, developerId,
      assignedBy: req.user._id, deadline, priority
    });
    await newTask.save();
    res.status(201).json(newTask);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

router.post('/tasks/create', authorize('Admin', 'Project Manager'), async (req, res) => {
  try {
    const newTask = new Task({
      projectId: req.body.projectId,
      feedId: req.body.feedId,
      performerId: req.user._id, // always use logged-in user
      targetUsers: req.body.assignedDevelopers,
      details: req.body.details
    });
    await newTask.save();
    res.status(201).json({ message: "Task inserted into tasks table!" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;